export default [
  "Help I'm being harassed!",
  "Help I'm being ... harassed?",
  "Stop being so racist.",
  "One short message for man, one internal timeout for botkind.",
  "Yikes! I'm getting spammed!",
  "Help! I'm drowning in pings!",
  "Easy there, tiger! Give me a break.",
  "Whoa, I'm only a bot, not a superhero!",
  "Too many pings! I need a nap.",
  "Ping overload! Bot needs rest.",
  "Oof, that's a lot of attention!",
  "Bot down! Bot down! Too many pings!",
  "I'm flattered, but please slow down.",
  "Ping frenzy! Bot needs a breather.",
  "I need some personal space too!",
  "I'm feeling a bit overwhelmed here!",
  "Hold your horses! I'm still processing.",
  "Ping storm detected! Seeking cover.",
  "Hey, I'm only virtual. Give me a break!",
  "Ping flood alert! System overload.",
  "I'm just a bot, not a machine gun target!",
  "Slow and steady wins the race, right?",
  "Phew! I need a timeout too.",
  "Overloaded with pings! Please wait.",
  "Whoa, easy on the pings!",
  "Hey, I need a cooldown too!",
  "So many pings, so little time.",
  "I'm just one bot! Be gentle.",
  "Give me a moment to catch up!",
  "I'm here! No need to spam.",
  "Ping jam detected. Slow down!",
  "Easy there! Too many pings.",
  "Let me catch my virtual breath.",
  "Ping traffic jam! Please wait.",
  "I need a ping vacation.",
  "Ping limit reached! Please wait.",
  "Overwhelmed with pings! Help!",
  "Ping chaos! Slow down, please.",
  "One ping at a time, please.",
  "Hey, I'm not a ping-pong ball!",
  "I need a breather. Too many pings.",
  "Hold up! Too many pings.",
  "Ping overload! Taking a break.",
  "Please, no more pings for a bit!",
  "I'm on a ping break. Be right back.",
  "Ping limit exceeded! Stand by.",
  "Too many pings! I need a timeout.",
  "Ping overload! Please hold.",
  "I need a ping break! One moment.",
  "Ping storm warning! Slow down.",
  "Help! I'm being pinged too much!",
  "Ping overload! Give me a sec.",
  "Ping limit reached! Cooling down.",
  "Easy with the pings! I'm just a bot.",
  "Whoa! Too many pings at once.",
  "Hold on! Too many pings!",
  "Ping panic! Please hold off.",
  "Ping explosion! Cooling down.",
]
